{% set name = "pybtexnbib" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pybtexnbib-{{ version }}.tar.gz
  sha256: a9b865643c91153a26169e9f234d8a87e8daf76fdb98a141ca660e0aac178843

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7.1,<4.0.0
    - pybtex >=0.24.0,<0.25.0
    - pybtexris >=0.1.2,<0.2.0

test:
  imports:
    - pybtexnbib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rbturnbull/pybtexnbib
  summary: A pybtex plugin for NBIB/Medline/PubMed files
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rbturnbull
    - vinisalazar
